=== api-evangelist/apache-openmeetings/json-schema/apache-openmeetings-invitation-dto-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-openmeetings/refs/heads/main/json-schema/apache-openmeetings-invitation-dto-schema.json",
  "title": "InvitationDTO",
  "description": "InvitationDTO schema from Apache OpenMeetings REST API",
  "type": "object",
  "properties": {
    "email": {
      "type": "string"
    },
    "firstname": {
      "type": "string"
    },
    "lastname": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "subject": {
      "type": "string"
    },
    "roomId": {
      "type": "integer",
      "format": "int64"
    },
    "passwordProtected": {
      "type": "boolean"
    },
    "password": {
      "type": "string"
    },
    "valid": {
      "type": "string",
      "enum": [
        "ONE_TIME",
        "PERIOD",
        "ENDLESS"
      ]
    },
    "validFrom": {
      "type": "string"
    },
    "validTo": {
      "type": "string"
    },
    "languageId": {
      "type": "integer",
      "format": "int64"
    }
  }
}

=== api-evangelist/apache-openmeetings/examples/apache-openmeetings-invitation-dto-example.json
{
  "email": "user@example.com",
  "firstname": "Example Name",
  "lastname": "Example Name",
  "message": "example",
  "subject": "example",
  "roomId": 1234,
  "passwordProtected": true,
  "password": "example",
  "valid": "ONE_TIME",
  "validFrom": "500123",
  "validTo": "500123",
  "languageId": 1234
}
