=== api-evangelist/apache-openmeetings/json-schema/apache-openmeetings-room-dto-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-openmeetings/refs/heads/main/json-schema/apache-openmeetings-room-dto-schema.json",
  "title": "RoomDTO",
  "description": "RoomDTO schema from Apache OpenMeetings REST API",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "name": {
      "type": "string"
    },
    "tag": {
      "type": "string"
    },
    "comment": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "CONFERENCE",
        "PRESENTATION",
        "INTERVIEW"
      ]
    },
    "capacity": {
      "type": "integer",
      "format": "int64"
    },
    "appointment": {
      "type": "boolean"
    },
    "confno": {
      "type": "string"
    },
    "demo": {
      "type": "boolean"
    },
    "closed": {
      "type": "boolean"
    },
    "demoTime": {
      "type": "integer",
      "format": "int32"
    },
    "externalId": {
      "type": "string"
    },
    "externalType": {
      "type": "string"
    },
    "redirectUrl": {
      "type": "string"
    },
    "moderated": {
      "type": "boolean"
    },
    "waitModerator": {
      "type": "boolean"
    },
    "allowUserQuestions": {
      "type": "boolean"
    },
    "allowRecording": {
      "type": "boolean"
    },
    "waitRecording": {
      "type": "boolean"
    },
    "audioOnly": {
      "type": "boolean"
    },
    "hiddenElements": {
      "uniqueItems": true,
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "TOP_BAR",
          "CHAT",
          "ACTIVITIES",
          "FILES",
          "ACTION_MENU",
          "POLL_MENU",
          "SCREEN_SHARING",
          "WHITEBOARD",
          "MICROPHONE_STATUS",
          "USER_COUNT"
        ]
      }
    },
    "files": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/RoomFileDTO"
      }
    },
    "public": {
      "type": "boolean"
    }
  }
}

=== api-evangelist/apache-openmeetings/examples/apache-openmeetings-room-dto-example.json
{
  "id": 1234,
  "name": "Example Name",
  "tag": "example",
  "comment": "example",
  "type": "CONFERENCE",
  "capacity": 1234,
  "appointment": true,
  "confno": "example",
  "demo": true,
  "closed": true,
  "demoTime": 1234,
  "externalId": "500123",
  "externalType": "example",
  "redirectUrl": "https://example.com",
  "moderated": true,
  "waitModerator": true,
  "allowUserQuestions": true,
  "allowRecording": true,
  "waitRecording": true,
  "audioOnly": true,
  "hiddenElements": [
    "TOP_BAR"
  ],
  "files": [
    {}
  ],
  "public": true
}
