=== api-evangelist/apache-openmeetings/json-schema/apache-openmeetings-user-dto-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-openmeetings/refs/heads/main/json-schema/apache-openmeetings-user-dto-schema.json",
  "title": "UserDTO",
  "description": "UserDTO schema from Apache OpenMeetings REST API",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "login": {
      "type": "string"
    },
    "password": {
      "type": "string"
    },
    "firstname": {
      "type": "string"
    },
    "lastname": {
      "type": "string"
    },
    "rights": {
      "uniqueItems": true,
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "ADMIN",
          "GROUP_ADMIN",
          "ADMIN_CONFIG",
          "ADMIN_CONNECTIONS",
          "ADMIN_BACKUP",
          "ADMIN_LABEL",
          "ROOM",
          "DASHBOARD",
          "LOGIN",
          "SOAP"
        ]
      }
    },
    "languageId": {
      "type": "integer",
      "format": "int64"
    },
    "address": {
      "$ref": "#/components/schemas/Address"
    },
    "timeZoneId": {
      "type": "string"
    },
    "externalId": {
      "type": "string"
    },
    "externalType": {
      "type": "string"
    },
    "pictureUri": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "USER",
        "LDAP",
        "OAUTH",
        "EXTERNAL",
        "CONTACT"
      ]
    }
  }
}

=== api-evangelist/apache-openmeetings/examples/apache-openmeetings-user-dto-example.json
{
  "id": 1234,
  "login": "example",
  "password": "example",
  "firstname": "Example Name",
  "lastname": "Example Name",
  "rights": [
    "ADMIN"
  ],
  "languageId": 1234,
  "address": {},
  "timeZoneId": "500123",
  "externalId": "500123",
  "externalType": "example",
  "pictureUri": "https://example.com",
  "type": "USER"
}
