=== api-evangelist/apache-openmeetings/json-schema/apache-openmeetings-appointment-dto-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/apache-openmeetings/refs/heads/main/json-schema/apache-openmeetings-appointment-dto-schema.json",
  "title": "AppointmentDTO",
  "description": "AppointmentDTO schema from Apache OpenMeetings REST API",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "title": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "start": {
      "type": "string",
      "format": "date-time"
    },
    "end": {
      "type": "string",
      "format": "date-time"
    },
    "description": {
      "type": "string"
    },
    "owner": {
      "$ref": "#/components/schemas/UserDTO"
    },
    "inserted": {
      "type": "string",
      "format": "date-time"
    },
    "updated": {
      "type": "string",
      "format": "date-time"
    },
    "deleted": {
      "type": "boolean"
    },
    "reminder": {
      "type": "string",
      "enum": [
        "NONE",
        "EMAIL",
        "ICAL"
      ]
    },
    "room": {
      "$ref": "#/components/schemas/RoomDTO"
    },
    "icalId": {
      "type": "string"
    },
    "meetingMembers": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/MeetingMemberDTO"
      }
    },
    "languageId": {
      "type": "integer",
      "format": "int64"
    },
    "password": {
      "type": "string"
    },
    "passwordProtected": {
      "type": "boolean"
    },
    "connectedEvent": {
      "type": "boolean"
    },
    "reminderEmailSend": {
      "type": "boolean"
    }
  }
}

=== api-evangelist/apache-openmeetings/examples/apache-openmeetings-appointment-dto-example.json
{
  "id": 1234,
  "title": "example",
  "location": "example",
  "start": "2026-04-19T10:00:00Z",
  "end": "2026-04-19T10:00:00Z",
  "description": "Example description",
  "owner": {},
  "inserted": "2026-04-19T10:00:00Z",
  "updated": "2026-04-19T10:00:00Z",
  "deleted": true,
  "reminder": "NONE",
  "room": {},
  "icalId": "500123",
  "meetingMembers": [
    {}
  ],
  "languageId": 1234,
  "password": "example",
  "passwordProtected": true,
  "connectedEvent": true,
  "reminderEmailSend": true
}
